### ISSUE TITLE
update how we pull education data from AirTable

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#101]
L23 have made a view for us as previously recommended. We may wish to extract data from here in the future

**Comment by gilesdring** [comment]
Original and new data here @ODILMichelle 

[schools_events.csv](https://github.com/open-innovations/leeds-2023/files/11153449/schools_events.csv)
[schools_events.new.csv](https://github.com/open-innovations/leeds-2023/files/11153450/schools_events.new.csv)

**Comment by gilesdring** [comment]
Changes that this has introduced to the data can be seen in this commit

https://github.com/open-innovations/leeds-2023/commit/6489a48b8c180d7f2f885111ee20d4ce005f0b00

**Comment by gilesdring** [comment]
Need to reintroduce fields

**Comment by gilesdring** [comment]
This is now done as per https://github.com/open-innovations/leeds-2023/commit/013db7a4be2b36a1ffd1d6cd77afdd89399513d9

#102 will add teacher data.
