### ISSUE TITLE
Reconcile ballot entry figure

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#106]
There are different numbers showing in the headline stats on The Awakening page (https://data.leeds2023.co.uk/metrics/events/awakening/) and microsite home page (https://data.leeds2023.co.uk/)

2374 vs 2421

**Comment by gilesdring** [comment]
I think this is individual vs individual + group.

**Comment by ODILMichelle** [comment]
Made tweaks to language on each of the pages. Sufficient for now.
