### ISSUE TITLE
Fix pop-up labels on hexmaps when viewed on mobile

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#111]
Picked up by L23, and to some degree replicated by me. 

Using both Firefox & Chrome on phone, Calverley & Farsley are cut off (see below). 

L23 report  Bramley and Stanningley also cutting off, although I see their label getting close to the edge but not cutting off. Asked what browser/phone combo they are using to help us solve this. 

When looking at volunteers on the phone, I also struggle with Pudsey - I can't see the number of applications recieved. 

![Image](https://user-images.githubusercontent.com/88284441/233616436-2afb6dc6-9476-44e4-8802-837504ca275c.png)

**Comment by ODILMichelle** [comment]
@gilesdring are you happy for this to be considered ready?

**Comment by gilesdring** [comment]
Yes

**Comment by slowe** [comment]
@gilesdring In OI Lume Charts the standard hex map tooltips should fit to the screen properly. See e.g. [custom tooltips](https://open-innovations.github.io/oi-lume-charts/samples/map/hex-cartogram/#example-9) and [hex labels](https://open-innovations.github.io/oi-lume-charts/samples/map/hex-cartogram/#example-2).

**Comment by gilesdring** [comment]
We will need to either switch hexmaps to standard version or implement the same logic in the L23 hexmap viz type.

**Comment by gilesdring** [comment]
Closed as a result of @slowe updating to the OI Lume Viz version of the hexmaps
