### ISSUE TITLE
Extract, process & transform 'MY LEEDS Schools Grants

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#115]
We will be amending existing 'Summer Community Grants' page to become a general community grants page, containing two hexmaps (Schools Grants & Summer Community Grants)

As such, the data to drive visualisation should live somewhere here: https://github.com/open-innovations/leeds-2023/tree/main/docs/metrics/community-grants

Form: ‘My LEEDS Schools Grants Application Form’ / myLeedsSchoolsGrantsApplication

**Comment by ODILMichelle** [comment]
@gilesdring is this ready, or do you need additional information?

**Comment by gilesdring** [comment]
If we're adding as a call-out, it should be ok to go.

**Comment by ODILMichelle** [comment]
Excellent point - and well remembered from yesterday. I am checking with L23 about whether to add this to call outs or the community grants page (recommending the latter approach). 

Will update you.

**Comment by ODILMichelle** [comment]
This should be good to go now @gilesdring - but see first post above regarding change to plans for this data.

 Added it to ready - feel free to send it elsewhere if you disagree!

**Comment by gilesdring** [comment]
Have processed file to provide individual columns + a total responses and updated page to present the my_leeds_grant_app data (as was). Ready to add additional viz as required - have slightly reformatted and have put in a headline for the other grant.

**Comment by ODILMichelle** [comment]
Thanks for this - will unblock the other visualisation. 

Relatedly, will pick up with L23 the fact that the schools applications at present do not seem to have a postcode associated with them.
