### ISSUE TITLE
Prepare data extract to enable visualisation of pupils engaged per ward

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#118]
Currently blocking #119

**Comment by ODILMichelle** [comment]
@gilesdring are you happy for us to add this to ready ahead of next sprint?

**Comment by gilesdring** [comment]
Yes, should be ok

**Comment by gilesdring** [comment]
Updating data in engagements_by_ward

Can now remove dependency on original schools data

**Comment by ODILMichelle** [comment]
Thanks. Lets pick the removal of that dependence as part of actions related to #125 and #126
