### ISSUE TITLE
Check volunteer data has updated

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#120]

**Comment by ODILMichelle** [comment]
@gilesdring can you check this has worked please?

**Comment by gilesdring** [comment]
Gaaah. It did not work. Keep open until it does! Will check again tomorrow...

**Comment by ODILMichelle** [comment]
PING

**Comment by gilesdring** [comment]
No.

So far, I have tried the following configs in the batch jobs with the following results:

| Setting of path | `~/rosterfy/ exists | Result |
|----------------|-------------------|-------|
| `rosterfy` | Yes | Files placed in `~/rosterfy/rosterfy/` |
| `rosterfy/` | Yes | Files placed in `~/rosterfy/rosterfy/` |
| blank | Yes | Files placed in `~` |

**Comment by ODILMichelle** [comment]
PING

**Comment by gilesdring** [comment]
Have essentially given up understanding what is actually happening here - I think there may be a Rosterfy defect, as it seems that any path you put in is automatically doubled. I have leant into this and download not from the `rosterfy/` directory, but `rosterfy/rosterfy/`

This ticket is consequently closed, but need to raise one with Rosterfy. I'm not guaranteeing this won't happen again!
