### ISSUE TITLE
Create Page(s) for Partner and Promote Events

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#122]
To include:

Partner

- [x] Count of Partner Events
- [x] Map of location of Partner Events (pulled from Partner Programme View on AirTable)
- [x] Number of Partner Events over time (pulled from Partner Programme view on AirTable)

Promote
- [x] Count of Promote Events
- [x] Map of location of Promote Events (where this can be gleaned)
- [x] Number of Promote Events over time

Blocked by #123

**Comment by gilesdring** [comment]
Data prep in #150

**Comment by gilesdring** [comment]
@taz-chiles This is ready to start, at least. I'm not completely convinced by the data that I've extracted, but propose we make a start and use that to have the discussion about data quality / content.

You should find `/metrics/events/partner/` and `/metrics/events/promote/` folders with `_data` directories. You should be able to plot number of events by ward and over time from those. Maybe not yet aggregated over time. No information about attendees that I can see.

**Comment by taz-chiles** [comment]
I have created a new branch for now and pushed changes to  main/122-create-pages-for-partner-and-promote-events

The bare bones are on there for each, a headline event count, hexmap with events per ward and a line chart of events over time. They're both identical for now and need some content. 

Looking into the data, there are several events (15 from partner and 14 promote) missing a ward code therefore currently not shown on the map. 

The sum of Partner events in by_ward (25) and by_month (22) are different, however the two values are the same for Promote. 

Will have a chat with @ODILMichelle this afternoon about this ticket and #133

**Comment by taz-chiles** [comment]
Proposing we close this ticket as completed then I'll create new tasks for the above, and for the actions that came out of my meeting with Sarah last week. Thoughts? @ODILMichelle @gilesdring

**Comment by taz-chiles** [comment]
Closing #122 as completed.
