### ISSUE TITLE
Extract, Transform and Process Data for partner & promote events page(s)

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#123]
We defined what we hope to see here: https://docs.google.com/document/d/1bebTOrMsDT7uD8x6rwuAf7ysjMVnbkqtTcDIsZ9GzI0/edit#

I will re-confirm with L23 that they want to see this done & will update this ticket when it is unblocked and @gilesdring can act on it

**Comment by ODILMichelle** [comment]
Will need to check data extract with L23 before visualising it.

**Comment by gilesdring** [comment]
One page for partner and one for present.

**Comment by gilesdring** [comment]
Have now added partner core data 

https://github.com/open-innovations/leeds-2023/tree/main/data/metrics/events/partner-events

and prepared data for site

https://github.com/open-innovations/leeds-2023/tree/main/docs/metrics/events

I think this is ready for visualisation...
