### ISSUE TITLE
Create schools grants hexmap & amend Summer Community Grants page

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#130]
To be added to My Leeds Summer Community Grants page, and this page amended to 'Community Grants': https://data.leeds2023.co.uk/metrics/community-grants/

Headline figures on page:

- [x] Applications for Summer Community Grants
- [x] Applications for My Leeds Schools Grants

Three hexmaps to be on page:

- [x] Two existing 'My LEEDS Summer Community Grants (LA & Ward)
- [x] Newly created 'My LEEDS Schools Grants' (Leeds Ward)

Headline figure on metrics landing page: https://data.leeds2023.co.uk/metric/

- [x] Total applications for grants (i.e. summer community grants applications + schools grants applications)

Blocked by #115

**Comment by ODILMichelle** [comment]
Further progress on this is blocked for the time being. There are no postcodes associated with the data in github. 

Have asked L23 about this, but @gilesdring could you do me a favour and quickly check the form builder to check that we're not missing a new column?

**Comment by gilesdring** [comment]
Of course, the schools grants form has schoolPostcode in the form, rather than postcode, and there is test data in there...

**Comment by gilesdring** [comment]
I've put in a test rejection (if postcode == test), but I output a warning if it is used. Ideally they'd clean up that data at source.

**Comment by ODILMichelle** [comment]
Thanks for this @gilesdring - and for adding the additional hexmaps. 

Have asked L23 to remove test data at source & will ask them for their views & words (including whether we need schools grants by LA). Added this to #131
