### ISSUE TITLE
Ensure social media stats are updating appropriately

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#132]

**Comment by taz-chiles** [comment]
Figures have been updated, however Sprout appears to have lost LinkedIn stats from 14th April. Investigating this..

**Comment by taz-chiles** [comment]
Hi Michelle - yes we were aware that the data returned but is still missing during that period. That's what the comment refers to. I assume that we're not going to recover the missing, more accurate data during that period but it's not the end of the world. I can amend the comment wording if it is unclear

LinkedIn data was missing from the Sprout Social feed from 15/04/2023 to 02/05/2023. Actual figures were higher during this period, we are working with LEEDS 2023 to determine the reason for this and recover the missing data.

**Comment by ODILMichelle** [comment]
Lets have a quick chat about this today. I'll drop you a call at some stage?

**Comment by gilesdring** [comment]
@ODILMichelle Will tweak language on site
