### ISSUE TITLE
Create a page for 'The Barn' Signature event(s)

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#133]
Following outline agreed here: https://docs.google.com/document/d/1bebTOrMsDT7uD8x6rwuAf7ysjMVnbkqtTcDIsZ9GzI0/edit#

Can show:

- [x] Number of events & Activities (Airtable MB work out what event & Activities, and go back to L23 with this list)

- [x] Attendances: Look @ TicketTailor which shows stuff people paying for. Need to explain this is a fraction however of people getting involved with it.

- [x] Headline number of responses to Barn Raiser & Wowser, with a link to call-put page

Other activities:

- [x] Dreambuilders (Community workshops part of CLE)
- [x] 3 or 4 School Days - handed over to schools to come in. (circa 180 pupils), will be in Airtable.

- [ ] Volunteers - lots of volunteers involved. Are we able to pull what they have been involved (related to shifts?)

**Comment by ODILMichelle** [comment]
@gilesdring had following email from L23. 

"Do you want me to send a spreadsheet containing ticket purchasers postcode info and no of tickets booked or can you get that through ticket tailor?". Let's pick this up when we can.

**Comment by gilesdring** [comment]
Have extracted all event data from Airtable and all ticket order data from Ticket Tailor in to working directory.

Begun looking at what we can usefully report

Scheduled events in here

https://github.com/open-innovations/leeds-2023/blob/main/scripts/metrics/events/scheduled/events.ipynb

Tickets in here

https://github.com/open-innovations/leeds-2023/blob/main/scripts/metrics/events/ticketing/tickets.ipynb

**Comment by gilesdring** [comment]
Have some processed data for this - events (count and attendances by date, and count of events by ward). Stored in https://github.com/open-innovations/leeds-2023/tree/main/docs/metrics/events/the_barn/_data

Could likely do with sense checking with L23, but can make a start on the first part of this.

**Comment by ODILMichelle** [comment]
Thanks for this @gilesdring. 

I've made a few amendments to what is above - @taz-chiles do you think you could make a start on this? L23 would love to get this sorted by 27th June, so we need to get on a first version of it this week if possible!

**Comment by taz-chiles** [comment]
Here is a first version of the Barn metrics page: https://data.leeds2023.co.uk/metrics/events/the_barn/

There are some tweaks to make, but feel free to let me know your comments if there's anything to pick up before we speak this afternoon @ODILMichelle

**Comment by taz-chiles** [comment]
The Barn MVP is done, with a few things to pick up

- Adding in volunteering numbers and shifts completed 
- Currently Dreambuilders and School Day figures are hard coded, need to amend pipelines to extract from Airtable
- Add in limitations
- Awaiting content from Leeds 2023 
- Add a description beneath the hexmap containing the number of events without a ward code similar to https://data.leeds2023.co.uk/metrics/schools/

**Comment by taz-chiles** [comment]
Proposing we close this and I'll open new tickets for the above, and actions out of meeting with Sarah @ODILMichelle @gilesdring

**Comment by taz-chiles** [comment]
Closing #133 as completed.
