### ISSUE TITLE
Query missing LinkedIn data from Sprout Social

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/leeds-2023#136]
LinkedIn data was missing from 15th April in the latest Sprout Social download. 

Causing a drop off in social media charts on the metrics page 

![Image](https://user-images.githubusercontent.com/97239140/236167492-4a2b38f7-9e80-4046-8736-2d86053372e9.png)

Email sent to Leeds 2023 (03/05/2023) to query and resolve the missing data

**Comment by taz-chiles** [comment]
Haven't heard back from social media contact at Leeds 2023, however LinkedIn data is now back in the Sprout feed. 

Data is still missing from 15/04 - 02/05, I will add this to the limitations section.

**Comment by ODILMichelle** [comment]
We now need the missing data - and are awaiting whether or not this is possible to gain. 

@taz-chiles - is there anything we need to do here?

**Comment by taz-chiles** [comment]
Closing ticket as this is covered by #186
