### ISSUE TITLE
Add limitation to social media page explaining LinkedIn data issue

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#138]
Need to publically explain #136 - and then remove limitation once this is resolved

**Comment by taz-chiles** [comment]
LinkedIn data has been restored however data wasn't recovered. I have added a limitation to the social media page. 


![Image](https://github.com/open-innovations/leeds-2023/assets/97239140/caa4213f-3344-4f36-8127-cc44de808503)


@ODILMichelle

**Comment by ODILMichelle** [comment]
I think this is done & can be closed now?
