### ISSUE TITLE
Create a 'Signature Event' page to capture collective data/info about signature events

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#142]
Along the lines of Partner & Promote ( #122)

Will then inform what is added to #32 

At present this will be pulling together The Awakening (already published) and #133

**Comment by gilesdring** [comment]
Data prep in #150

**Comment by gilesdring** [comment]
Headlines

* Total events
* Total attendances
* Total tickets sold

Graphs

* Aggregated events and attendances graphs (by date)
* Aggregated events and attendances hexmaps (by ward)
* Tickets sold by ward of residence
* Tickets sold by date of event

**Comment by taz-chiles** [comment]
Initial version added to https://data.leeds2023.co.uk/metrics/events/signature/

May wish to convert graphs to cumulative event count. Will share with client for feedback and content

**Comment by taz-chiles** [comment]
Shared updated pages with client on 9th August
Nudge sent on 15th August, no feedback on the pages as yet.
Follow up sent today
