### ISSUE TITLE
Explore & extract data from the three analytics systems that L23 are using

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#143]
GA, Clarity and Plausible

**Comment by gilesdring** [comment]
Plausible is here:

https://plausible.io/leeds2023.co.uk - seems to be open dashboards!

I've been added to the GA property for Leeds 2023.

**Comment by gilesdring** [comment]
Pipeline created and putting some minimal data (page views) into the `docs/metrics/web-analytics/_data` directory. Ready for work on #144 and #145

**Comment by gilesdring** [comment]
Write manual update process

**Comment by taz-chiles** [comment]
Closing this ticket as completed #143
