### ISSUE TITLE
Extract Dreambuilders and School Days from Airtable

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/leeds-2023#155]
https://data.leeds2023.co.uk/metrics/events/the_barn/

On the Barn Signature Event page, the Dreambuilders and School Days are hard coded from a count in Airtable, however these need to be extracted in the pipelines. Update the events scripts to pull events with these tags.

**Comment by gilesdring** [comment]
@taz-chiles Describe the counting mechanism and we can update the pipeline
