### ISSUE TITLE
Add Partner, Promote and Signature events data to Ward Coverage dashboard

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/leeds-2023#163]
Once we're happy with the data metrics to be shown on: 

https://data.leeds2023.co.uk/metrics/events/promote/
https://data.leeds2023.co.uk/metrics/events/partner/
https://data.leeds2023.co.uk/metrics/events/the_barn/

They should be added to the Community Engagement dashboard

**Comment by gilesdring** [comment]
* Signature events, tickets sold
* Promote events
* Partner events

**Comment by taz-chiles** [comment]
Signature events, tickets sold and The Barn attendance figures added to Resident engagement. 

Number of events for Signature and Partner events added to Ward-focussed Initiatives

Unable to add Promote events because we do not have ward data for these

**Comment by taz-chiles** [comment]
Closing #163 as completed
