### ISSUE TITLE
Update data source for Partner events

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/leeds-2023#169]
LEEDS 2023 have confirmed the correct data source for Partner events: 

Promote/Partner base in Airtable - ‘Promote - What’s On’ table - ALL data . 
https://airtable.com/app40BfxSxQFxA3MC/tblCt3WsEYjOlfjiv/viwQCvJhvj1IKuMzM?blocks=hide

Leeds 2023 will confirm whether the correct view is ‘All events’ or ‘By Date Entered’ and which filter to apply - querying ‘LI pull through’
We think we should filter by ‘Partner/Promote’ tag however need to confirm that this is reliable.

‘Venue Postcode’ field has now been added so we should pull this instead of taking the postcode from the address field. 
We do not have attendance data for these events.

Headlines: 
Counts of events 
Events by ward 

Line chart:
Events over time

**Comment by gilesdring** [comment]
Partner event page created - have not yet added wards with event headline

https://data.leeds2023.co.uk/metrics/events/partner/

Output of transform pipeline is here, showing some of the other metrics they might have been interested in

https://github.com/open-innovations/leeds-2023/blob/main/working/output/promote-events-transform.ipynb

Can be sent over for review @taz-chiles
