### ISSUE TITLE
Validate data sources for The Barn page

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#170]
We will validate the data we’re displaying about the barn and check nothing appears to have been tagged inappropriately in Airtable

**Comment by gilesdring** [comment]
The data for The Barn now uses the same processing as My LEEDS 2023

Output of pipeline is stored here including counts of tags presented, missing audience numbers and duplicate / missing ward information.

https://github.com/open-innovations/leeds-2023/blob/main/working/output/the-barn.ipynb

Updated page is here

https://data.leeds2023.co.uk/metrics/events/the-barn/

@taz-chiles  Propose sharing the above with L23 for their info

**Comment by taz-chiles** [comment]
@gilesdring brilliant cheers Giles - will send all updates along to L23 this afternoon

**Comment by taz-chiles** [comment]
27/07 client agreed that the Barn figures we are presenting on the site look accurate and we are using the correct filters. 

I believe we can consider this done and will open a new ticket if anything else emerges.
