### ISSUE TITLE
Update Impact dashboard

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#172]
We recognise that some of the data on this page is not correct at present - and solving the data on this page will take us beyond Monday. To ensure everything that is being shown is accurate, for Monday, the easiest fix we can make by CoP Friday is:

* We will replace the ‘Events Held’ and ‘Engagements with Residents’ metrics on the dashboard with the number of Partner and Promote events. 
* We will also replace the community engagement hexmap with another hexmap showing engagements per ward e.g. the percentage of schools engaged with per ward. 
* We also discussed updating the hard-coded metrics on the Impact Dashboard, therefore if you send over an up to date number of secured funders, we’ll get this updated.

**Comment by gilesdring** [comment]
Funding update: secured funders = 49;  funding prospects = 80

**Comment by taz-chiles** [comment]
I've updated funding data and replaced the hexmap with school engagement. Replaced events held and residents engaged with Partner and Promote events, the figures will update when the data source is updated. 

![image](https://github.com/open-innovations/leeds-2023/assets/97239140/bc76b8bd-886b-4b86-b43c-8f6022beb40a)

**Comment by gilesdring** [comment]
Establish link to https://data.leeds2023.co.uk/metrics/schools/ to the hexmap

**Comment by taz-chiles** [comment]
Link has been added to /metrics/schools - via the panel title
