### ISSUE TITLE
Create new community engagement metrics page

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#180]
1. Download data from AirTable view https://airtable.com/appHAh7IYG6p2w5Yo/shrId61ACMYGBg78W/tblQDTK5iBUkn3C0q
2. Prepare cleansed view and summaries to drive visualisations
   * Include pipeline report to share with L23 to show data quality
3. Create new page with
   * headline of total events / attendances
   * hexmap of events / location and hexmap of attendances
   * line graph of events / attendances by month

**Comment by taz-chiles** [comment]
Community Engagement page will be updated as follows: 

Two pages:  

- [ ] Children and Young People renamed to Creative Learning? To confirm with Fiona 
- [ ] Community Engagement  

Headline figures: Number of Community Engagement events, number of attendances at Community Engagement events 

2 hexmaps:  

- [ ] Events by ward (airtable + MWMCMN, roadshows, ballot and hidden stories) 
- [ ] People: Total number of people attended in that ward by ward (airtable + MWMCMN, roadshows, ballot and hidden stories 
- [ ] Line graph – events over time. 

2022 work, ballot and hidden stories to remain the same.  

CA to provide copy on definition of community engagement event. 		 

Limitations: people who have specifically engaged with community engagement programme, not the whole programme.

**Comment by taz-chiles** [comment]
Closing #180 as completed
