### ISSUE TITLE
Add new Callout to pipeline

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#185]
A new Callout needs to be added. 

Form ID: guardiansOfLeedsCreativeCollab

Form name Guardians of Leeds Creative collaboration

Description: An opportunity for a poet or storyteller of ethnic diversity and/or diasporic lineage excited about discovering how space and community informs our identity

**Comment by gilesdring** [comment]
First thing to do is to add the new callout to this list

https://github.com/open-innovations/leeds-2023/blob/94b8a5bcbb1597083de332d6e1891dc58e31b76d/scripts/metrics/callouts/extract.py#L36-L51

These keys will be renamed from camelCase to snake_case and saved as files in the `working` directory

If you need to rename any callouts (e.g. to combine multiple into one), you can do that by updating the dict here:

https://github.com/open-innovations/leeds-2023/blob/94b8a5bcbb1597083de332d6e1891dc58e31b76d/scripts/metrics/callouts/transform.py#L14-L18

You can specify the human-readable name in this file:

https://github.com/open-innovations/leeds-2023/blob/main/docs/metrics/callouts/_data/names.yml

Add new line charts in here

https://github.com/open-innovations/leeds-2023/blob/main/docs/metrics/callouts/_data/series.yml


Hopefully this is enough to progress @taz-chiles

**Comment by taz-chiles** [comment]
New callout added, closing as done.
