### ISSUE TITLE
Extract ticketing data for new Signature Event pages

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/leeds-2023#190]
Fiona has added some ticket tailor IDs in Airtable against Nest where project_name == "10 - Melt" and event_name == "Melt (run)". Start by extracting these IDs (they are comma separated) and pulling corresponding ticketing data for this event. 

Then we'll ask L23 to add IDs into Airtable for the remaining Signature events and we'll apply the same process. 

- [ ] Extract ticketing data from Nest events to test that we can pull ticketing data for the right events
- [ ] Extract data for Smeaton 300 and 
- [ ] Extract data for Children's Day

**Comment by gilesdring** [comment]
Have got a working MVP of this (does not yet write files, but prints tables into jupyter notebook

https://github.com/open-innovations/leeds-2023/blob/main/working/output/nest.ipynb

Looks like it'll be work, so can add the rest.

@taz-chiles We could do with agreeing where these files go by convention, then we can define an additional helper to write ticket data out.

**Comment by taz-chiles** [comment]
Closing #190 as completed
