### ISSUE TITLE
Create visualisation of Awakening attendees

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#21]

**Comment by ODILMichelle** [comment]
For information - from Ollie & Catherine at L23 (in case it informs visualisation approach taken)

a) if a ticket is used, ticket tailor will do that automatically. However, we do have some events without a definitive 'check in' so we might not get everybody for some of the events.
b) As people check out, it is compulsory to enter a postcode - we've done so for the evaluation and monitoring of engagement throughout the year.

**Comment by gilesdring** [comment]
MVP created at https://data.leeds2023.co.uk/metrics/events/awakening

Needs text and supporting detail

**Comment by ODILMichelle** [comment]
I think the visualisation itself looks good, with a small caveat that I have noticed that if you hover near the side of one hex you can see the hexagon vibrating rapidly. I don't know if this creates a risk for those with epilepsy.

I find the 'skip to bottom of chart'/'skip to the top of chart' labels confusing and I'm not sure what they do (Note: Have only tested on a desktop screen). 

1 - First 'skip to bottom' takes me effectively to the second visualisation (awakening attendees by LA). 
2 - First 'skip to top' takes me down the page as well, but less far than 1 above.
3 - Second 'skip to bottom' takes me to ballot entries by ward of resident
4 - Second 'skip to top', places Awakening Attendees by LA at the top of my page

The below skip to top and skip to bottom entries also make odd movements around page - and even once we have navigation fixed, we might need to be clearer in the text describing these options. 

Do we need this navigational option?

**Comment by ODILMichelle** [comment]
Additional note - the navigational option of skip to bottom/top appears to now be in place across multiple charts on the site, and may be causing issues. See also: https://github.com/open-innovations/leeds-2023/issues/39

**Comment by gilesdring** [comment]
The skiplinks are accessibility additions. They are to enable keyboard navigation, and we need to add them to all charts. We ought to make them disappear unless they're focussed (per the skiplink at the top of the page, which you probably didn't know was there!)

There is a sight issue given the static header (which is inherited from L23 main site design) that a skiplink navigates to a slightly weird place. This being a genetic issue with all hexmaps etc, there should be a separate ticket to track this, which is a way of me saying I won't fix this as part of this ticket!

**Comment by gilesdring** [comment]
Skip links on chart (required accessibility feature). Presentation / behaviour tracked in #40

**Comment by ODILMichelle** [comment]
Fixing skip link navigation now tracked in #41

**Comment by gilesdring** [comment]
Have fixed other issues, hence closing this as done.

**Comment by ODILMichelle** [comment]
It's not specifically relevant for this ticket, but slightly related so will add for completeness. 

L23 questioned the Awakening data shared on the Awakening page - highlighting that the numbers in the hexmaps didn't add up to attendees in their data. We are showing 4366 attendees on the hexmaps (which are Leeds city council and Leeds city region), made up of (roughly):

- 3666 (ish) in Leeds wards
- 700 from non-Leeds, Leeds city regions (or 4366 from the total Leeds city regions). 

Reviewed their data quickly, and it is the same (at a skim) as that which is checked into github. Checked this by a) calculating total attendees, which were the same at 5102 b) looking at a few specific wards in the Leeds area and calculating whether attendee totals matched). 

Further reviewed the data & found 400 or so attendees which no known postcode, and a reasonable number of attendees attending from wards and local authorities outside the hexmaps (e.g. London, Manchester, Cheshire). 

Agreed that we would made a text update to the site to ensure any confusion was removed & working on this now.

Identifie
