### ISSUE TITLE
Refactor callouts pipeline to make explicit extracts for known callouts

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#23]

**Comment by gilesdring** [comment]
@ODILMichelle To check with Fiona

**Comment by gilesdring** [comment]
Callouts currently explicitly included directly in code by adding name of form builder table to https://github.com/open-innovations/leeds-2023/blob/58d3c0b015f16ea763d6841b2c8a97af64d9b4a1/scripts/metrics/callouts/extract.py#L25-L34

Display names defined in https://github.com/open-innovations/leeds-2023/blob/58d3c0b015f16ea763d6841b2c8a97af64d9b4a1/docs/metrics/callouts/_data/names.yml

Could potentially externalise

**Comment by ODILMichelle** [comment]
Emailed Fiona to check if this list is correct: https://data.leeds2023.co.uk/metrics/callouts/

**Comment by ODILMichelle** [comment]
@gilesdring could you review this list at some stage - ideally before 3pm tomorrow when I catch-up with Fiona.  

Fiona has mentioned that the below should also be displayed: 
- ‘become a barnraiser’
- ‘lift the lid’
- ‘apply for a 10 day acting course’

She also mentioned a ‘My Leeds Community Grants’ but I will look to understand this tomorrow, to identify if it is something we can/should visualise and how!

**Comment by gilesdring** [comment]
Found the names:

**become a barnraiser**

becomeABarnRaiser

**lift the lid**

liftTheLidAudio
liftTheLidWritten

**apply for a 10 day acting course**

nytPlayhouseActingCourse


Community Grant app - to be separate ticket

myLeedsGrantApp
myLeedsGrantAppAudiovisual

**Comment by ODILMichelle** [comment]
Confirmed these are the correct forms, and confirmed that we should combine liftTheLidAudio & liftTheLidWritten. 

There may be other future instances in which 'written' and 'audio' routes are shown - L23 do this on some calls so as to increase accessibility for applicants

**Comment by ODILMichelle** [comment]
I am talking with Fiona on Monday about how L23 might add an identifier somewhere on forms used for call outs (and other items) to specifically identify callouts, thus allowing us to automate this system rather than have them email and update us each time.

**Comment by ODILMichelle** [comment]
@gilesdring we have had a request to add additional call outs:

Gill Cranshaw exhibition - I think this form is called "Commission Application: Any Work That Wanted Doing curated by Gill Crawshaw" 
Meet Leeds Lab - I think this is called "meet leeds lab" - and that there is both an audio and written version of this call out. 

I say that those are the names of the forms, but I can only state this with low confidence as it is what is reported. I recognise that all other forms I have seen have no spaces in them.

**Comment by ODILMichelle** [comment]
@gilesdring 

In addition the note I made yesterday, we have now been made aware that L23 will not be adding any other data to call outs. This is due to limited dev time at L23. 

Instead, will be creating a manual system for updating us on call outs to add. FY's team will be signing all forms off and as part of this process will have an action to send over new call out to OI. This will contain: 

- Name of call out
- Call out form name
- 1 sentence description (see https://github.com/open-innovations/leeds-2023/issues/60)
