### ISSUE TITLE
Update media metrics visualisations

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#25]
Change the visualisations as follows:

- Headlines
  - [x] Add aggregate 'total estimated circulation' UV (Unique Visitors) + Audience
  - [x] Add colours to headline boxes
  - [x] Remove headlines breaking down by scope
  - [x] Keep total articles
- Breakdowns 
  - [x] Add stacked chart of articles by scope to replace current montlhy media rticles bar chart (the yellow one)
  - [x] Remove Media Coverage by scope
  - [x] Convert media coverage by medium to black barchart
  - [x] Amend 'amount of coverage' label to be 'number of articles/appearances'
- Michelle to work with L23 to add technical narrative (Mon 27th)
  - [ ] Definitions of UV and Audience and Total Estimated Circulation, as well as limitations around these

**Comment by gilesdring** [comment]
Pre-requisites:

- [ ] Call with Anys @ AMA

**Comment by ODILMichelle** [comment]
From Anys:
Print and broadcast content is measured as audience reach based upon the circulation or viewership of those outlets or programmes. Online content is measured as unique visitors per month for the outlet.

Audience and UV stats don't break down any further for different programmes on the same station / sections of a website

**Comment by ODILMichelle** [comment]
Meeting with Claire didn't take place on Friday. Looking to get this booked in for w/c 13th

**Comment by ODILMichelle** [comment]
Followed up to try to get this call booked.

**Comment by gilesdring** [comment]
Yep. Happy with this.

**Comment by ODILMichelle** [comment]
Moving to ready as not heard anything back. Will mention to L23 that this is a blocker, but we are moving regardless, when I speak with them tomorrow.

**Comment by ODILMichelle** [comment]
Mentioned this is a blocker, but that we are moving on it regardless. L23 will chase internally.

**Comment by ODILMichelle** [comment]
Commented out unwanted metrics (commented rather than removed so that we can sense check this with Claire).

Added colour to headline figures

**Comment by ODILMichelle** [comment]
@gilesdring should have brought it up in our quick convo earlier, but we also agreed that we would make no charts about 'total estimated circulation' as there is some skeptism about that figure. We will however add a headline figure for that.

**Comment by gilesdring** [comment]
Have fixed the metrics pipeline to present data about type of outlook by scope (local, regional, etc) and date to drive generation. This will also create the estimated circulation, which looks like it was manually added, and would have been wiped out on the nightly run.

Page also updated to show bar chart, plus removed all the stuff we don't need any longer.

@taz-chiles I think I've completed all the visualisation changes. Over to @ODILMichelle for text!

**Comment by gilesdring** [comment]
Have also added a `humanise` filter (can be used in place of the `localise` filter), which does this sort of thing...

![Image](https://user-images.githubusercontent.com/1731108/228085303-a1951ccf-7225-4b96-8685-e2c4ef870c52.png)
