### ISSUE TITLE
[BLOCKED] Extract schools data from Airtable

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#27]
Extract based on `Workstream == CLE`

**Comment by ODILMichelle** [comment]
Update on conversation with Chris:
We are looking to pull Event type == CLE - Creative Learning session. 

However:
a) there are some items currently labelled as this which are incorrect. Chris is addressing this internally
b) There is one item which should be included which show as "CLE - Creative Learning session,Public Event - Performance" in excel extract. This is likely because the entry has two tags. There may be future events which have multiple tags, one of which is "CLE - Creative Learning session" which should be included in the schools data

**Comment by ODILMichelle** [comment]
Hey @gilesdring, L23 got in touch today about this and points raised on https://github.com/open-innovations/leeds-2023/issues/28

L23 will be adding data to Airtable as proposed in the email e.g. there will be one entry per event with multiple schools tagged. They are aware that this means we will not be able to visualise pupils engaged by ward - and I will make an amendment to our definition of done to match this.

**Comment by ODILMichelle** [comment]
Thanks for this @gilesdring. Reflections:

1. After I said "Event type == CLE - Creative Learning session" in the comment above, you corrected me to point out that it needed to include CLE etc, not ==, when I highlighted the fact that there maybe multiple tags on activities (given that it seemed csv downloads merged these tags. 
2. We have a lot of 'test school activity' which L23 will need to remove once we're happy we've got the right extract
3. Looking through the data it's interesting to note that there are a bunch of activities which I would consider not to be schools level activities e.g. row 2, Leeds Beckett Freshers Fair, rows 21 and 30 which appear to be teachers meetings. 
4. I'll take a look through the data extract you previously shared which pulled master events out of AirTable and compare and contrast to check what we're pulling out is what we expect to see based on previous conversations.

I will share a copy of the extract with Chris once we're happy with this to check with him

**Comment by gilesdring** [comment]
Pipelines now more or less working (MVP style)

Data is processed to this form: https://github.com/open-innovations/leeds-2023/blob/main/data/metrics/schools/schools_events.csv


Then prepared for presentation in here

https://github.com/open-innovations/leeds-2023/tree/main/docs/metrics/schools/_data

summary.json - top level stats

engagements_by_week = time series of engagements with particpants / schools, including cumulative. Note this is not equivalent to events - if there is one event, but 5 schools turned up to it, we'd end up with a count of 5 here.

schools_engagement_counts = number of engagements with each schools

**Comment by ODILMichelle** [comment]
@gilesdring - As mentioned before there is one item that is on the Master Events list, that isn't being pulled through into the extract so far. 

This is Feel the Music: Feel the Music (AirTable ID 401). 

We will have a blocker on this item at present, as it is a future event (July 2023). However it is also our only event with two tags in the system at present. 

I don't know if you want to test the extraction process with the 'past events only' filter removed to test if we are extracting events with two tags - or if you want to pick this up in the future.

**Comment by ODILMichelle** [comment]
Email sent to L23 re: this data

**Comment by ODILMichelle** [comment]
@gilesdring i have feedback from L23 on the email I sent them. Would be good to chat about this today if possible

**Comment by gilesdring** [comment]
Will need to pick up in next sprint. Kicking back into Ready column

**Comment by ODILMichelle** [comment]
Sounds good, contact at L23 is off today anyway, so we won't get any further response from them until later in week.

**Comment by ODILMichelle** [comment]
Email sent and as work is progressing on #28, I think we can consider this closed now.
