### ISSUE TITLE
Add community engagement metric to homepage

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#29]

**Comment by ODILMichelle** [comment]
My general feeling is a) how many people have been engaged b) how many events have taken place c) how many Signature events have taken place.

**Comment by gilesdring** [comment]
I think signature events is a different dataset. I have a slight preference for residents engaged as the most important headline metric...

**Comment by ODILMichelle** [comment]
Can we discuss this before we begin to implement this? I ask as I have a few questions I would like to explore related to which events and activities we are capturing 'residents engaged' at. (I badly explained some of it here, mostly as a note to myself: https://trello.com/c/0klSc0uf/192-add-additional-layers-to-community-engagement-dashboard)

**Comment by taz-chiles** [comment]
Similar to issue #51, I could add the same 'residents engaged' metric to the homepage with a link to the community engagement dashboard?

**Comment by taz-chiles** [comment]
Closing as completed

**Comment by ODILMichelle** [comment]
Could we change the colour of this box? The light green to me seems to merge into the background a little a) in comparison to the other brighter colours b) with the light green heading being used for the splash at the top of the page.

**Comment by taz-chiles** [comment]
I have updated the colours on the homepage and added a cycler @gilesdring so that the tiles rotate through cyan, yellow and magenta. Hopefully that looks better and means it doesn't blend in with the rest of the page too much @ODILMichelle
