### ISSUE TITLE
Add volunteering shifts to homepage

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#30]
Depends on #24, and integration of volunteering shifts / hours into main volunteering page

**Comment by taz-chiles** [comment]
I have updated the homepage to include a 'volunteering hours' metric. However there's an issue with grid layout not behaving @gilesdring, maybe could grab 5 minutes in delivery session

**Comment by taz-chiles** [comment]
Fixed the grid layout. I kept 'volunteering hours' rather than 'volunteering shifts' however I can update this if necessary

**Comment by gilesdring** [comment]
@taz-chiles We might need to back this out for the moment - the volunteering shifts stuff will move, and the data is not confirmed yet. Could you comment out?

**Comment by taz-chiles** [comment]
Hey @gilesdring I have commented out the volunteering shifts panel on the homepage for now - can add back in later if need be
