### ISSUE TITLE
Add signature event attendance to Ward Coverage dashboard

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#32]
Update pipeline for ward coverage to add signature event, attendance and tickets sold to appropriate layers.

**Comment by ODILMichelle** [comment]
For information - from Ollie & Catherine at L23 (in case it informs visualisation approach taken)

a) if a ticket is used, ticket tailor will do that automatically. However, we do have some events without a definitive 'check in' so we might not get everybody for some of the events.
b) As people check out, it is compulsory to enter a postcode - we've done so for the evaluation and monitoring of engagement throughout the year.

**Comment by ODILMichelle** [comment]
Don't move on this for now, superceeded by #107 for the time being. Kept because we want to move on this in the future.

**Comment by ODILMichelle** [comment]
Keeping this blocked for now as I want to talk with L23 before we move on this.
