### ISSUE TITLE
Visualise community grants application data

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#38]
Hexmap visualisation showing how many people applied for community grants from each ward. Done should be defined here: https://trello.com/c/s0ACLOKi/131-visualise-community-grants-leeds23-sharing-with-wards

**Before closing item, please create a new ticket to develop the text for this page.**

**Comment by ODILMichelle** [comment]
Sub-set of call-out data: 
myLeedsGrantApp
myLeedsGrantAppAudiovisual

**Comment by ODILMichelle** [comment]
Name of Page to be: My LEEDS Summer Community Grants

**Comment by gilesdring** [comment]
Community grants data processed from the form-builder database in the same way as the callouts data.

Site build data here -> 

https://github.com/open-innovations/leeds-2023/tree/main/docs/metrics/community-grants/_data

30 mins work so far.

@taz-chiles @ODILMichelle over to you to build a page!

**Comment by ODILMichelle** [comment]
Moving back to ready as we have the data

**Comment by ODILMichelle** [comment]
Visualisation of community grants by ward complete - have asked L23 to a) review b) respond to a few questions, namely: 

- Do they want any other data to be displayed about locations of applications as there were a few applications which were either 'Unknown' or from outside Leeds (I believe the grant scheme was only designed for those within Leeds but things may have changed). If so, I would like us to capture some information similar to the volunteers data
- Are applications still open, and is it worth showing a line chart or barchart of applications for this over time? (I ask as it looked like there was an application over the last week or so)
