### ISSUE TITLE
Ensure all boxes on L23 impact dashboard have a line above number stating 'since MON-YR'

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#43]
In January we agreed we would trial this as a means of expressing start dates for each activity, recognising that some e.g. media coverage will have much longer lead in times. 

It might not work, but it would be good to test this in one or two instances.

**Comment by ODILMichelle** [comment]
This didn't come up in convo with Fiona - perhaps we consider this obsolete at this point in time, unless it re-emerges as an issue. Thoughts @taz-chiles ?

**Comment by taz-chiles** [comment]
Agreed, it hasn't been mentioned for some time now. I'm erring on the side of keeping the dashboard uncluttered but if it is mentioned as a priority we can add it in

**Comment by ODILMichelle** [comment]
Lets close this for now, and re-add if it emerges again.
