### ISSUE TITLE
Add text to the Awakening page

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#46]
The Awakening page is finished bar a final review with Fiona. 

Will ask Fiona for words for this page, rather than trying to create them ourselves.

**Comment by ODILMichelle** [comment]
Fiona has shared text, I am reviewing this.

**Comment by ODILMichelle** [comment]
Text Fiona has shared, and comments I am making are on Google Drive: https://docs.google.com/document/d/1yMQVCTlFXeWPQUP0UhzoyfmnKM4X8c4KIB8GrZXzXmU/edit#heading=h.mei033xuh882

Will talk Fiona through this today

**Comment by ODILMichelle** [comment]
Agreed this is too promotional at present, Michelle to make some amendments & propose these to Fiona

**Comment by ODILMichelle** [comment]
@gilesdring I am looking at 'Where ballot entries came from' on https://data.leeds2023.co.uk/metrics/events/awakening/

There is a line I am keen to understood in more detail: "This chart shows where individual ballot entries came from" - I believe this means individual ballot entries are displayed here, but group ballots entries at schools are not displayed. 

Could you confirm this?

**Comment by ODILMichelle** [comment]
@gilesdring I need some input into one of the existing known issues and limitations on this page:

"Each individual ballot entry is allocated up to four seats. Group ballot entries are submitted with a requested number of seats. The tickets total uses the upper figure for individual ballot entries, combined with the explicitly requested number of group ballot seats."

Can you confirm that the 'Seats allocated' calculation effectively is 
= **number of ballot submissions * 2** (where L23 were only allocating 2 tickets) + **number of ballot submissions * 4** (where this period of time) + **explicitly requested number of group ballot seats**

**Comment by gilesdring** [comment]
Not quite. It is `ballot entries * 4 + group tickets requested`

**Comment by ODILMichelle** [comment]
Thanks, does this mean the known issue should therefore be: 

"Calculated 'Seats allocated' may not be exact. While group ballot entries were submitted with a requested number of seats. At different stages during the ballot process, individual entries were allocated either two or four seats. 'Seats allocated' uses the upper figure for individual ballot entries, combined with the explicitly requested number of group ballot seats."

This allows us to pick up on this, and specifically name the known issue.
