### ISSUE TITLE
Solve issue related to duplicate HTML IDs on charts

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#47]
Related to accessibility issues 206, 212, 219

https://odileeds.sharepoint.com/:x:/s/OpenInnovationsPrivate/EbvmdR31FK1Bk3N2nM5XmbABlv3j7AGBCfZ5SBgdLhgDQw?e=cJ3jfK

When adding charts, sometimes the charts have duplicate IDs

This affects

https://data.leeds2023.co.uk/metrics/volunteers/ (#offered)
https://data.leeds2023.co.uk/metrics/social-media/
https://data.leeds2023.co.uk/dashboard/impact/

**Comment by ODILMichelle** [comment]
@gilesdring do you need anything from me to make this ready?

**Comment by taz-chiles** [comment]
This is done, closing as completed
