### ISSUE TITLE
Fix contrast on Social Media page

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#48]
Accessibility issue 217 https://odileeds.sharepoint.com/:x:/s/OpenInnovationsPrivate/EbvmdR31FK1Bk3N2nM5XmbABlv3j7AGBCfZ5SBgdLhgDQw?e=0k8f5Z

Very low contrast - Pink and Gold text (active filter)
Foreground: #FFDD00
Background: #FF00A6
Ratio: 2.68:1

**Comment by ODILMichelle** [comment]
@gilesdring could you take a few mins to review whether this is complete.

**Comment by gilesdring** [comment]
Looks like still an issue.

![image](https://user-images.githubusercontent.com/1731108/234495705-c037e67f-937f-49c1-8859-13b9e68d35a3.png)

Have some thoughts about how to do this. 

Plan: Implement a Lume filter which, given a colour will pick the appropriate contrast colour. Use this wherever there are colour contrast issues in the first instance.

This can be moved to ready

**Comment by gilesdring** [comment]
On second thoughts - not over-complicating this - it's a one-line change...
