### ISSUE TITLE
Fix styling on impact dashboard

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/leeds-2023#49]
Making the necessary accessibility changes has altered some of the styling on the impact dashboard.

These need to be amended once actions from the accessibility audit have been completed.

https://data.leeds2023.co.uk/dashboard/impact/

**Comment by gilesdring** [comment]
@taz-chiles @ODILMichelle Close this when you're happy with how it looks.

**Comment by ODILMichelle** [comment]
Love it other than one quick question: Do we need the underlined text when we hover. 

I presume it is built as a nudge that these are also hyperlinks, but it feels slightly odd to me. Can share with Fiona on Monday however to see how she feels?

**Comment by gilesdring** [comment]
It's an accessibility thing, yes. See what Fiona thinks. We could limit it to (say) the heading elements.

More like this



![Image](https://user-images.githubusercontent.com/1731108/224480843-f18281e7-d35d-4ed8-b6fd-8e0fc9d1d3d9.png)

That would be a case of changing this code 

https://github.com/open-innovations/leeds-2023/blob/e38587393614561f81e9d337f18551944dfb361b/docs/_components/dashboard/impact/panel.njk#L41-L43

To be 

```css
    &:hover h2 {
      text-decoration: underline;
    }
```

This assumes that `h2`s are in every panel, which they ought to be.

**Comment by ODILMichelle** [comment]
Thanks, will pick this up when I speak with her. 

M

**Comment by gilesdring** [comment]
Fixing now...
