### ISSUE TITLE
Switch the impact dashboard view of community engagement to residents engaged rather than events hosted

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#51]

**Comment by taz-chiles** [comment]
Do we want to pull residents engaged including or excluding schools data? @gilesdring @ODILMichelle 

The number of events held currently does not include schools so will need to update for both.

**Comment by ODILMichelle** [comment]
My initial reaction is without schools data, because we can add 'pupils engaged' at a future date (once we have that data sorted). I could be convinced otherwise though, if someone has a strong view?

**Comment by taz-chiles** [comment]
Perfect, I've updated without schools data for the time being, can always add them in later. Closing this task as done

**Comment by ODILMichelle** [comment]
Hey @taz-chiles looking at the impact dashboard  it now appears that we have both 'Residents Engaged' and 'Total Attendances' at the top - which are of course the same number. 

I was wondering if it was as a result of actions on this ticket. I think when I read the ticket I was expecting us to:

a) keep total number of events as a metric on the top left hand side of the Dashboard and  
b) Amend the Community Engagement hexmap from 'events held' to 'attendances by residents at events'

@gilesdring however wrote the ticket and so I might be entirely wrong!

**Comment by taz-chiles** [comment]
All good, so to clarify on the top row of the dashboard we'll have: 

- Events held
- Total attendances 
- Community engagement hexmap showing count of resident attendances instead of event count

@ODILMichelle @gilesdring

**Comment by ODILMichelle** [comment]
Can you check with Giles @taz-chiles? That is how I interpreted the ticket, but he wrote it :)

**Comment by ODILMichelle** [comment]
Moved to in review as we're discussing whether it is done.

**Comment by gilesdring** [comment]
We need to lose the second box (entitled total attendances). As @ODILMichelle points out, they're the same thing. Attendances is misleading, as this figure includes volunteers who have signed up, and may include call-out data in future. It's about resident engagement. I originally proposed the change as I think that it's a more meaningful measure.

**Comment by taz-chiles** [comment]
Thanks for clarifying, I've made the changes above, now showing: 

Events held
Residents engaged 
Community engagement hexmap showing count of resident attendances instead of event count

If we're all happy with this I'll close the ticket

**Comment by ODILMichelle** [comment]
I think we are - bar the changes we'll need to pick up re: how we define events and engagements across the whole site. 

@gilesdring ?

**Comment by taz-chiles** [comment]
Grand, I'll close this one for now then and anything new we can pick up as a separate ticket.
