### ISSUE TITLE
Amend 'Volunteer Offer' to 'Volunteer offer' on impact dashboard

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#54]
Stray capital on the 'O'.

**Comment by ODILMichelle** [comment]
@gilesdring - with the changes taking place with the volunteer pipeline will we still be displaying the number of volunteer positions offered?

If not, this issue is obsolete.

**Comment by ODILMichelle** [comment]
Looking at the impact dashboard, it appears the volunteer offers box is now missing. We may have removed this to replace it with 'volunteers confirmed' which might make sense, or perhaps have turned it invisible (as space remains for it). 

Could you check @taz-chiles ?

**Comment by taz-chiles** [comment]
Good spot thank you! Fixed now
