### ISSUE TITLE
Add 'across Y opportunities' to headline stat on call out page

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#59]
L23 are keen to see 'X responses over Y opportunities' as the headline stat on the main call out page, moving us from 'X opportunities' which is the current stat displayed

**Comment by ODILMichelle** [comment]
Exact format/text of what L23 is keen to see: 

Headline box:

Responses
[number]
Total number of responses to Y opportunities

This will require a) adding in the functionality to calculate how many responses are present as well as b) some text changes. Note that it is 'Responses' not 'Callout responses' in both line 1 and line 3 of the box.

**Comment by ODILMichelle** [comment]
Alternatively, we could add a second headline box, showing total number of call outs. I quite like this as an idea so that we don't have just one headline figure.

**Comment by ODILMichelle** [comment]
@taz-chiles is this something you could pick up?

**Comment by taz-chiles** [comment]
I have added a second headline box showing the number of callouts (12) - let me know if this is different to what you had in mind @ODILMichelle

**Comment by taz-chiles** [comment]
Yep, I noticed this - have updated the wording. If that's all good I'll close the ticket :)
