### ISSUE TITLE
Make it easy for WYCA to see where call out responses are coming from

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#61]
WYCA are funding a few projects which are related to call outs. They want to see where call out responses are coming from. 

We use a table for something similar on volunteers page: https://data.leeds2023.co.uk/metrics/volunteers/

And a hexmap for a wider section of councils for Awakening: https://data.leeds2023.co.uk/metrics/events/awakening/

**When complete, please open a new ticket to complete copy for this section.**

**Comment by ODILMichelle** [comment]
When I met L23 they didn't specify if this should be displayed as:

a) a hexmap displaying all call out responses from WYCA/wider section of councils
b) table showing call outs and responses from specific WYCA councils. 

@gilesdring, if we are happy to proceed with this, would you like me to clarify which they prefer, or do you have a strong preference?

**Comment by ODILMichelle** [comment]
From call 16th March:

L23 are specifically keen to show responses from across WYCA councils in response to 'The Barn'/Wow related call outs. Exactly what this looks like is undefined and in our gift. 

At a minimum we would need either a hexmap or table showing responses to The Barn/WOW related call-outs. 

Whether we went over and above (e.g. a table breaking down responses to all call outs from across WYCA, or going beyond that to show the whole Leeds City Region) is for us to decide. 

If we chose to show WYCA rather than LCR we might need to come up with some explanation as we used LCR for The Awakening attendees: https://data.leeds2023.co.uk/metrics/events/awakening/

**Comment by gilesdring** [comment]
Data is already reported by LA in https://github.com/open-innovations/leeds-2023/blob/main/docs/metrics/callouts/_data/responses_by_la.csv. Will extend to have the following columns:

`la_code`, `responses`, `barn_plus_wow_responses`

`barn_plus_wow_responses` will be the sum of callout responses to `become_a_barn_raiser` + `become_a_wowser`

**Comment by gilesdring** [comment]
Have updated https://github.com/open-innovations/leeds-2023/blob/main/docs/metrics/callouts/_data/responses_by_la.csv and https://github.com/open-innovations/leeds-2023/blob/main/docs/metrics/callouts/_data/responses_by_ward.csv as discussed. They contain columns per callout (dynamic, based on callouts imported), a `responses` column with the total, and a `barn_plus_wow_responses` which is the sum of `become_a_barn_raised` and `become_a_wowser`.

**Comment by gilesdring** [comment]
Over to you @ODILMichelle

**Comment by ODILMichelle** [comment]
Shared with client to review
