### ISSUE TITLE
Identify possible data/visualisations to publish as part of the Q1  quarterly reporting

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#69]
Prerequisites

- [x] Find out if we have an updated draft report
- [x] Find out what meeting is on 31st
- [x] Read draft reports
- [x] Understand different data present within each reporting mechanism
- [x] Attend meeting on the 31st March
- [x] Identify possibly visualisations to publish & how we might do this 
- [x] Discuss this and reach agreement with Fiona, Penny & Abigail

**Comment by ODILMichelle** [comment]
Spoke with L23:

It is expected that what we saw in Feb was a report for The Awakening, rather than a draft quarterly report. 

L23 gave data to TAA last week and are expecting to receive a draft quarterly report ahead of 31st March. On 31st expect for all parties to talk it through. L23 will need various internal sign offs, and then to go to LCC mid April. They are checking whether it is on the cards to publish these reports openly. 


L23 checking appetite for publishing data openly, recognising that much of it will be data they own.

**Comment by ODILMichelle** [comment]
Report on sharepoint, have identified visualisations I think that might be of interest

**Comment by ODILMichelle** [comment]
Summary of what visualisations I believe we should add can be found in Sharepoint. Will follow up with L23 about this the other side of Easter. 

One thing to discuss @gilesdring is that there is a possibility that L23 would want us to host PDF reports (or summary reports) of the material which has gone to the Board. This will be discussed at the next Board meeting. Do you foresee any concerns about us doing that, given our philosophical stance?

**Comment by ODILMichelle** [comment]
Trying to find time with Fiona to discuss this on a call.

**Comment by gilesdring** [comment]
I have no issue in principle with the hosting of PDFs! In some ways it would be good to have these under source control somehow.

**Comment by ODILMichelle** [comment]
This may well slip into sprint 5, as I am not getting the chance to catch-up with L23 until 3pm Tuesday.
