### ISSUE TITLE
Review how we are displaying 'page last updated' on Social media page

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#72]
Some pages on the site have a 'page last updated' note on the page. e.g. 

![Image](https://user-images.githubusercontent.com/88284441/225361719-5725ce82-d6f8-4e7d-a4e1-96fdaa27b19a.png)

Social media page does this by including, in just one block, which feels odd. Not least it means the numbers are not aligned appropriately.

![Image](https://user-images.githubusercontent.com/88284441/225362660-fa530980-5892-4944-91d1-0f7b4b074e1f.png)

Does this mean the other blocks might have different dates? 

Related to this, Claire has asked that we make it very clear what the start date is, so that we're not just saying 'as of', but also picking up 'since when'. 

I don't have a strong view on what the the best approach is - the updated date in the headline box looks good, but might look too much if it were in all blocks - and is unlikely to also work if we add a 'since when' number.

**Comment by ODILMichelle** [comment]
@gilesdring Like the other ticket I just tagged you in, I know you were looking at page updates yesterday, so thought I would flag this ticket to you.

**Comment by gilesdring** [comment]
- [ ] Remove date from the block

**Comment by ODILMichelle** [comment]
Waiting to review #71 and changes across whole site so we can review how we proceed with this.

**Comment by ODILMichelle** [comment]
Blocked by #137
