### ISSUE TITLE
Resolve the 404 error when you click through on either funding metric on the Impact Dashboard

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#73]
As we have hidden the funding metrics page, when you now click through on either funding related metric on the Impact Dashboard you get a 404 error. 

This feels a little amateur, and I was wondering how we best get around it - given we want to keen the funding metric page hidden for now

**Comment by taz-chiles** [comment]
Hey - in the meantime, we could just remove links on the impact dashboard to funding pages? The rest will remain the same but the funding metrics won't link anywhere - we can add them back in when the fundraising page is unhidden again.

**Comment by ODILMichelle** [comment]
Hello! So I just had a chat with L23 about funding/fundraising data - and it appears they had forgotten they had asked us to display funding data which was updated on a quarterly basis on the impact dashboard. And they were proposing removing metrics relating to funding from the impact dashboard.

Have reshared the notes with them, and they are reviewing this internally to reach a decision (and will look to see if we can manage this by Monday). 

In meantime, agree that we can just remove the links. 

Thanks.

**Comment by taz-chiles** [comment]
No prob, for now I've removed the links on the impact dashboard and we can chat about removing fundraising metrics when we get an update

**Comment by ODILMichelle** [comment]
Thanks for that. 

Lets close this, and add something new if/when that comes up.
