### ISSUE TITLE
Switch out volunteering metrics on impact dashboard for Total hours and Volunteers appointed

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#77]
I think these are better metrics

Metrics are

* `shifts.summary.volunteer_hours.total_events`
* `by_week.columns.confirmed | last`

**Comment by ODILMichelle** [comment]
Kept number of applications & numbers confirmed. 

Lets discuss of shifts completed is more valuable to L23 than numbers engaged. Happy to ask Fiona if useful @gilesdring

**Comment by gilesdring** [comment]
Should this go back to Ready @ODILMichelle?

**Comment by ODILMichelle** [comment]
Been partially completed (i.e. adding confirmed volunteers). Keen to hear your case for total hours before going to discuss this with L23.

**Comment by ODILMichelle** [comment]
@gilesdring - just to let you know this is something I'm awaiting your thoughts on!

**Comment by gilesdring** [comment]
So - number of shifts === number of engagements with volunteers in a volunteering role. This is probably the truest metric, as turning up for a shift is a positive, whether that's for 15 minutes tending a stall somewhere, or 4 hours at an event.

However - number of volunteer hours will be a bigger number, and much more eye-catching and potentially easier to comprehend as a casual observer...

In brief - pros and cons on both sides, and I'm not strongly wedded to either. Apologies if at some point I gave the impression I was! ;-)

**Comment by taz-chiles** [comment]
Closing as not planned - we can open this again in future if it comes up in discussions again.
