### ISSUE TITLE
Amend metrics landing page 'callout' metric

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#80]
Following content comments from L23, I've amended "Callout" to "call out" across the appropriate metrics page. 

The metrics landing page however remains "callouts": https://data.leeds2023.co.uk/metric/

In making the content tweak on line 40 (https://github.com/open-innovations/leeds-2023/blob/main/docs/metrics/callouts/index.njk) to amend headline figure, I wondered if this meant that line 18 here was no longer referencing the correct thing (https://github.com/open-innovations/leeds-2023/edit/main/docs/pages/metrics/index.njk)

**Comment by ODILMichelle** [comment]
Sorry @gilesdring, not quite complete. 

It should be "Call out" not Callout" on this page: https://data.leeds2023.co.uk/metric/

**Comment by gilesdring** [comment]
That's set by the title of the Call Outs metrics page itself. Which is why that title is also still wrong.

**Comment by ODILMichelle** [comment]
Thanks, will sort that out.

Before I do, can you confirm that if I make the amendment to the title I won't break anything else.

M
________________________________

**Comment by gilesdring** [comment]
I have done it.
