### ISSUE TITLE
Clean up historic volunteer data

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#97]
L23 carried out a clean-up of their volunteer data removing a fair few profiles. We don't believe we have done the same to our system, which inflates the figures on data microsite

**Comment by ODILMichelle** [comment]
Hey @gilesdring - do you think you could take a look at this next week?

The reason for asking this is that ti would be good to get to the bottom of the discrepancy in volunteer figures between ourselves and TAA ASAP - in case they have some errors in their data and need to review such things

**Comment by gilesdring** [comment]
Volunteers not in Rosterfy now excluded from report.
